### ISSUE TITLE
log errors encountered during loading by HTTP error code or python error type

### ISSUE THREAD

**Issue by kislyuk** [HumanCellAtlas/query-service#220]
Possibly a reaction to the bundle being deleted in the course of ETL:
```
Traceback (most recent call last):
  File "/mnt/query-service/.venv37/lib/python3.7/site-packages/dcplib/etl/__init__.py", line 109, in get_files_to_fetch_for_bundle
    with open(f"{self.sd}/bundle_manifests/{bundle_uuid}.{bundle_version}.json") as fh:
FileNotFoundError: [Errno 2] No such file or directory: './bundle_manifests/7a865e5f-701c-4c47-8e1a-4c8abf540451.2019-07-10T110340.267000Z.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/query-service/dcpquery/db/__main__.py", line 71, in <module>
    **extractor_args
  File "/mnt/query-service/.venv37/lib/python3.7/site-packages/dcplib/etl/__init__.py", line 96, in extract
    bundle = future.result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/mnt/query-service/.venv37/lib/python3.7/site-packages/dcplib/etl/__init__.py", line 58, in extract_one
    bundle_uuid, bundle_version, fetched_files = self.get_files_to_fetch_for_bundle(bundle_uuid, bundle_version)
  File "/mnt/query-service/.venv37/lib/python3.7/site-packages/dcplib/etl/__init__.py", line 115, in get_files_to_fetch_for_bundle
    res.raise_for_status()
  File "/mnt/query-service/.venv37/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://dss.staging.data.humancellatlas.org/v1/bundles/7a865e5f-701c-4c47-8e1a-4c8abf540451?replica=aws
Makefile:126: recipe for target 'load' failed
make: *** [load] Error 1
```

**Comment by kislyuk** [comment]
There is a mode in the ETL for skipping 404's, but there is no classification for errors were encountered during loading bundles.

Refactoring this ticket.
