### ISSUE TITLE
Debug or improve logging for intermittent test failure in Travis build 1422

### ISSUE THREAD

**Issue by kislyuk** [HumanCellAtlas/query-service#277]
```
make build-chalice-config init-db migrate-db load-test-data
envsubst < iam/policy-templates/dcpquery-lambda.json > .chalice/policy-dev.json
cd .chalice; jq .app_name=env.APP_NAME < config.in.json > config.json
cd .chalice; for var in $EXPORT_ENV_VARS_TO_LAMBDA; do \
            jq .stages.dev.environment_variables.$var=env.$var config.json | sponge config.json; \
        done
cd .chalice; V=$(git describe --tags --always) jq .stages.dev.environment_variables.VERSION=env.V config.json | sponge config.json
cd .chalice; jq .stages.dev.tags.env=env.STAGE config.json | sponge config.json
cd .chalice; jq .stages.dev.tags.service=env.APP_NAME config.json | sponge config.json
cd .chalice; jq .stages.dev.tags.owner=env.OWNER config.json | sponge config.json
cd .chalice; jq .stages.dev.api_gateway_stage=env.STAGE config.json | sponge config.json
python -m dcpquery.db init
INFO:dcpquery.db:Initializing database at postgresql+psycopg2://travis:***@/dcpquery
INFO:dcpquery.db:Creating database
INFO:dcpquery.db:Initializing database
INFO:dcpquery.db:Migrating database at postgresql+psycopg2://travis:***@/dcpquery
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 000000000000, create tables
INFO  [alembic.runtime.migration] Running upgrade 000000000000 -> f86d2cea09a9, create tables
INFO  [alembic.runtime.migration] Running upgrade f86d2cea09a9 -> 51a8fb96ea24, create rules
INFO  [alembic.runtime.migration] Running upgrade 51a8fb96ea24 -> 7597ca0971e5, create db functions
INFO  [alembic.runtime.migration] Running upgrade 7597ca0971e5 -> 9fa7918d332b, rename processes to processes_for_graph
INFO  [alembic.runtime.migration] Running upgrade 9fa7918d332b -> e2b45add6f68, rename_bundle_and_file_tables
INFO  [alembic.runtime.migration] Running upgrade e2b45add6f68 -> b56789b3d784, create indices
INFO  [alembic.runtime.migration] Running upgrade b56789b3d784 -> 88bab7754636, add unique req to process_process combo
python -m dcpquery.db migrate
INFO:dcpquery.db:Migrating database at postgresql+psycopg2://travis:***@/dcpquery
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
python -m dcpquery.db load-test
INFO:tweak:Loaded configuration from /home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/hca/default_config.json
INFO:dcplib.etl:Scanning 38 bundles
INFO:dcplib.etl:Extracted bundles: 0 (0.0%, 0 errors)
........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................Traceback (most recent call last):
  File "/opt/python/3.7.1/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/python/3.7.1/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/travis/build/HumanCellAtlas/query-service/dcpquery/db/__main__.py", line 99, in <module>
    **extractor_args
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/dcplib/etl/__init__.py", line 102, in extract
    extracted_results.append(future.result())
  File "/opt/python/3.7.1/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/opt/python/3.7.1/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/opt/python/3.7.1/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/dcplib/etl/__init__.py", line 72, in extract_transform_one
    bundle_manifest_path=bundle_manifest_path, extractor=self)
  File "/home/travis/build/HumanCellAtlas/query-service/dcpquery/etl/__init__.py", line 36, in transform_bundle
    file_doc = json.load(fh)
  File "/opt/python/3.7.1/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/opt/python/3.7.1/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/opt/python/3.7.1/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/python/3.7.1/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Makefile:120: recipe for target 'load-test-data' failed
make: *** [load-test-data] Error 1
travis_time:end:0a2b7690:start=1567702944004438461,finish=1567703021925568182,duration=77921129721,event=before_script
[0K[31;1mThe command "make build-chalice-config init-db migrate-db load-test-data" failed and exited with 2 during .[0m

Your build has been stopped.
```

**Comment by mweiden** [comment]
@MDunitz can we close this?
